import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:speech_to_text/speech_to_text.dart' as stt;
import 'package:url_launcher/url_launcher.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try { await Firebase.initializeApp(); } catch (_) {}
  final store = await Store.load();
  await store.connectFirebase();
  runApp(DainPayApp(store: store));
}

String makeId() => '${DateTime.now().microsecondsSinceEpoch}_${Random().nextInt(999999)}';
String money(double v) => '${v.toStringAsFixed(2)} د.ل';
String phone218(String value) { var p = value.replaceAll(RegExp(r'[^0-9]'), ''); if (p.startsWith('00')) p = p.substring(2); if (p.startsWith('218')) return p; if (p.startsWith('0')) return '218${p.substring(1)}'; return p; }
String dateText(DateTime d) => '${d.day.toString().padLeft(2,'0')}/${d.month.toString().padLeft(2,'0')}/${d.year}';

class Customer {
  Customer({required this.id, required this.name, required this.phone, this.limit = 0});
  String id, name, phone; double limit;
  Map<String,dynamic> toJson()=>{'id':id,'name':name,'phone':phone,'limit':limit};
  factory Customer.fromJson(Map<String,dynamic> j)=>Customer(id:'${j['id']??''}',name:'${j['name']??''}',phone:'${j['phone']??''}',limit:(j['limit'] as num?)?.toDouble()??0);
}
class Tx {
  Tx({required this.id,required this.customerId,required this.type,required this.amount,required this.date,required this.note,this.receiptPath='',this.receiptUrl=''});
  String id,customerId,type,note,receiptPath,receiptUrl; double amount; DateTime date;
  Map<String,dynamic> toJson()=>{'id':id,'customerId':customerId,'type':type,'amount':amount,'date':date.toIso8601String(),'note':note,'receiptPath':receiptPath,'receiptUrl':receiptUrl};
  factory Tx.fromJson(Map<String,dynamic> j)=>Tx(id:'${j['id']??''}',customerId:'${j['customerId']??''}',type:'${j['type']??'debt'}',amount:(j['amount'] as num?)?.toDouble()??0,date:DateTime.tryParse('${j['date']}')??DateTime.now(),note:'${j['note']??''}',receiptPath:'${j['receiptPath']??''}',receiptUrl:'${j['receiptUrl']??''}');
}

class Store extends ChangeNotifier {
  late SharedPreferences prefs;
  final customers=<Customer>[]; final transactions=<Tx>[];
  String shop='DainPay — دَيْن';
  String whatsappMessage='السلام عليكم [الاسم]، تذكير لطيف بخصوص المتبقي عليكم قدره [المبلغ] د.ل.';
  String uid='',deviceId=''; bool firebaseReady=false,syncing=false,activated=false; DateTime? trialStart;

  static Future<Store> load() async {
    final s=Store(); s.prefs=await SharedPreferences.getInstance();
    s.shop=s.prefs.getString('shop')??s.shop; s.whatsappMessage=s.prefs.getString('whatsappMessage')??s.whatsappMessage;
    s.deviceId=s.prefs.getString('device_id')??''; if(s.deviceId.isEmpty){s.deviceId='DP-${DateTime.now().millisecondsSinceEpoch}-${Random().nextInt(999999)}';await s.prefs.setString('device_id',s.deviceId);}
    final ts=s.prefs.getString('trial_start'); if(ts!=null) trialStart=DateTime.tryParse(ts); else {trialStart=DateTime.now();await s.prefs.setString('trial_start',trialStart!.toIso8601String());}
    s.activated=s.prefs.getBool('activated')??false;
    try{final d=jsonDecode(s.prefs.getString('customers')??'[]') as List;s.customers.addAll(d.map((e)=>Customer.fromJson(Map<String,dynamic>.from(e))));}catch(_){ }
    try{final d=jsonDecode(s.prefs.getString('transactions')??'[]') as List;s.transactions.addAll(d.map((e)=>Tx.fromJson(Map<String,dynamic>.from(e))));}catch(_){ }
    return s;
  }
  int get trialDaysLeft { if(activated||trialStart==null)return 0; return max(0,10-DateTime.now().difference(trialStart!).inDays); }
  bool get locked => !activated && trialDaysLeft<=0;
  Future<void> connectFirebase() async { try { var u=FirebaseAuth.instance.currentUser; u??=(await FirebaseAuth.instance.signInAnonymously()).user; if(u==null)return; uid=u.uid; firebaseReady=true; await pullCloud(); await loadActivation(); } catch(_){firebaseReady=false;} notifyListeners(); }
  CollectionReference<Map<String,dynamic>> get customersRef=>FirebaseFirestore.instance.collection('users').doc(uid).collection('customers');
  CollectionReference<Map<String,dynamic>> get transactionsRef=>FirebaseFirestore.instance.collection('users').doc(uid).collection('transactions');
  Future<void> loadActivation() async { if(!firebaseReady)return; try{final d=await FirebaseFirestore.instance.collection('device_activations').doc(deviceId).get(); if(d.exists&&d.data()?['activated']==true){activated=true;await prefs.setBool('activated',true);}}catch(_){}}
  Future<void> pullCloud() async { if(!firebaseReady||uid.isEmpty||syncing)return; syncing=true; try{for(final d in(await customersRef.get()).docs){final c=Customer.fromJson(d.data());final i=customers.indexWhere((x)=>x.id==c.id);if(i<0)customers.add(c);else customers[i]=c;}for(final d in(await transactionsRef.get()).docs){final x=d.data();final raw=x['date'];final dt=raw is Timestamp?raw.toDate():DateTime.tryParse('$raw')??DateTime.now();final t=Tx(id:'${x['id']??d.id}',customerId:'${x['customerId']??''}',type:'${x['type']??'debt'}',amount:(x['amount'] as num?)?.toDouble()??0,date:dt,note:'${x['note']??''}',receiptPath:'${x['receiptPath']??''}',receiptUrl:'${x['receiptUrl']??''}');final i=transactions.indexWhere((z)=>z.id==t.id);if(i<0)transactions.add(t);else transactions[i]=t;}await saveLocal();}catch(_){}finally{syncing=false;}}
  Future<void> saveCloud() async { if(!firebaseReady||uid.isEmpty||syncing)return; syncing=true; try{final b=FirebaseFirestore.instance.batch();for(final c in customers)b.set(customersRef.doc(c.id),c.toJson());for(final t in transactions)b.set(transactionsRef.doc(t.id),{...t.toJson(),'date':Timestamp.fromDate(t.date)});await b.commit();}catch(_){}finally{syncing=false;}}
  Future<void> saveLocal() async {await prefs.setString('customers',jsonEncode(customers.map((e)=>e.toJson()).toList()));await prefs.setString('transactions',jsonEncode(transactions.map((e)=>e.toJson()).toList()));await prefs.setString('shop',shop);await prefs.setString('whatsappMessage',whatsappMessage);}
  Future<void> save() async {await saveLocal();notifyListeners();await saveCloud();}
  double balance(String id)=>transactions.where((t)=>t.customerId==id).fold(0.0,(a,t)=>a+(t.type=='debt'?t.amount:-t.amount));
  double debts(String id)=>transactions.where((t)=>t.customerId==id&&t.type=='debt').fold(0.0,(a,t)=>a+t.amount);
  double paid(String id)=>transactions.where((t)=>t.customerId==id&&t.type=='payment').fold(0.0,(a,t)=>a+t.amount);
  String risk(String id){final b=balance(id);if(b<=0)return'مسدد';final ds=transactions.where((t)=>t.customerId==id&&t.type=='debt').toList()..sort((a,b)=>a.date.compareTo(b.date));if(ds.isEmpty)return'حديث';final d=DateTime.now().difference(ds.first.date).inDays;if(d>90)return'خطر';if(d>30)return'متأخر';return'حديث';}
  Future<bool> activate(String code) async { if(!firebaseReady||code.trim().isEmpty)return false; final ref=FirebaseFirestore.instance.collection('activation_codes').doc(code.trim()); try{final ok=await FirebaseFirestore.instance.runTransaction<bool>((tx)async{final snap=await tx.get(ref);final data=snap.data();if(!snap.exists||data==null||data['used']==true)return false;final bound='${data['deviceId']??''}';if(bound.isNotEmpty&&bound!=deviceId)return false;tx.update(ref,{'used':true,'usedAt':FieldValue.serverTimestamp(),'usedDeviceId':deviceId});return true;});if(!ok)return false;await FirebaseFirestore.instance.collection('device_activations').doc(deviceId).set({'activated':true,'activatedAt':FieldValue.serverTimestamp(),'uid':uid});activated=true;await prefs.setBool('activated',true);notifyListeners();return true;}catch(_){return false;}}
  Future<String?> generateCode(String targetDevice) async {if(!firebaseReady||targetDevice.trim().isEmpty)return null;String code;do{code=(100000+Random().nextInt(900000)).toString();}while((await FirebaseFirestore.instance.collection('activation_codes').doc(code).get()).exists);await FirebaseFirestore.instance.collection('activation_codes').doc(code).set({'deviceId':targetDevice.trim(),'used':false,'createdAt':FieldValue.serverTimestamp()});return code;}
}

class DainPayApp extends StatelessWidget {const DainPayApp({super.key,required this.store});final Store store;ThemeData t(Brightness b)=>ThemeData(useMaterial3:true,brightness:b,colorSchemeSeed:const Color(0xFF0F5C6E),fontFamily:'Cairo');@override Widget build(BuildContext c)=>AnimatedBuilder(animation:store,builder:(_,__)=>MaterialApp(debugShowCheckedModeBanner:false,theme:t(Brightness.light),darkTheme:t(Brightness.dark),themeMode:ThemeMode.system,home:HomePage(store:store)));}

class HomePage extends StatefulWidget{const HomePage({super.key,required this.store});final Store store;@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{String q='',filter='all';int settingsTaps=0;DateTime? lastTap;
  void adminTap(){final now=DateTime.now();if(lastTap==null||now.difference(lastTap!).inSeconds>2)settingsTaps=0;lastTap=now;settingsTaps++;if(settingsTaps>=3){settingsTaps=0;showDialog(context:context,builder:(_)=>AdminGate(store:widget.store));}}
  @override Widget build(BuildContext context){final s=widget.store;final list=s.customers.where((c){final b=s.balance(c.id);final qq=q.isEmpty||c.name.contains(q)||c.phone.contains(q);final ff=filter=='all'||(filter=='debt'&&b>0)||(filter=='paid'&&b<=0);return qq&&ff;}).toList()..sort((a,b)=>s.balance(b.id).compareTo(s.balance(a.id)));final total=s.customers.fold(0.0,(a,c)=>a+max(0,s.balance(c.id)));return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:GestureDetector(onTap:adminTap,child:Text(s.shop,style:const TextStyle(fontWeight:FontWeight.w900))),actions:[IconButton(icon:const Icon(Icons.settings_outlined),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>SettingsPage(store:s))))]),body:ListView(padding:const EdgeInsets.all(12),children:[if(!s.activated)Card(color:s.trialDaysLeft<=3?Colors.orange.shade100:null,child:ListTile(leading:const Icon(Icons.timer_outlined),title:Text(s.locked?'انتهت الفترة التجريبية':'الفترة التجريبية'),subtitle:Text(s.locked?'فعّل التطبيق للاستمرار':'متبقٍ ${s.trialDaysLeft} أيام'),trailing:FilledButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ActivationPage(store:s))),child:const Text('التفعيل')))),Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:Stat('المتبقي',money(total))),Expanded(child:Stat('العملاء','${s.customers.length}'))]))),TextField(decoration:const InputDecoration(hintText:'بحث بالاسم أو الهاتف',prefixIcon:Icon(Icons.search)),onChanged:(v)=>setState(()=>q=v)),const SizedBox(height:8),Wrap(spacing:8,children:[ChoiceChip(label:const Text('الكل'),selected:filter=='all',onSelected:(_)=>setState(()=>filter='all')),ChoiceChip(label:const Text('عليهم دين'),selected:filter=='debt',onSelected:(_)=>setState(()=>filter='debt')),ChoiceChip(label:const Text('مسدد'),selected:filter=='paid',onSelected:(_)=>setState(()=>filter='paid'))]),const SizedBox(height:8),...list.map((c){final b=s.balance(c.id);return Card(child:ListTile(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>CustomerPage(store:s,customer:c))),title:Text(c.name,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${c.phone}\n${s.risk(c.id)} • دين ${money(s.debts(c.id))} • مسدد ${money(s.paid(c.id))}'),isThreeLine:true,trailing:Text(money(b),style:const TextStyle(fontWeight:FontWeight.w900))));})]),floatingActionButton:FloatingActionButton.extended(onPressed:s.locked?()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ActivationPage(store:s))):()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AddCustomerPage(store:s))),icon:Icon(s.locked?Icons.lock_outline:Icons.person_add_alt_1),label:Text(s.locked?'التفعيل':'عميل')));}}
class Stat extends StatelessWidget{const Stat(this.title,this.value,{super.key});final String title,value;@override Widget build(BuildContext c)=>Column(children:[Text(title),const SizedBox(height:4),Text(value,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900))]);}

class AddCustomerPage extends StatefulWidget{const AddCustomerPage({super.key,required this.store});final Store store;@override State<AddCustomerPage> createState()=>_AddCustomerPageState();}
class _AddCustomerPageState extends State<AddCustomerPage>{final n=TextEditingController(),p=TextEditingController(),l=TextEditingController();Future<void> save()async{if(n.text.trim().isEmpty)return;store.customers.add(Customer(id:makeId(),name:n.text.trim(),phone:p.text.trim(),limit:double.tryParse(l.text.replaceAll(',','.'))??0));await store.save();if(mounted)Navigator.pop(context);}late final Store store;@override void initState(){super.initState();store=widget.store;}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('إضافة عميل')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:n,decoration:const InputDecoration(labelText:'اسم العميل')),TextField(controller:p,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'رقم الهاتف')),TextField(controller:l,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'السقف الائتماني اختياري')),const SizedBox(height:20),FilledButton(onPressed:save,child:const Text('حفظ'))])));}

class CustomerPage extends StatelessWidget{const CustomerPage({super.key,required this.store,required this.customer});final Store store;final Customer customer;Future<void> wa()async{final msg=store.whatsappMessage.replaceAll('[الاسم]',customer.name).replaceAll('[المبلغ]',money(store.balance(customer.id)));final u=Uri.https('wa.me','/${phone218(customer.phone)}',{'text':msg});if(await canLaunchUrl(u))await launchUrl(u,mode:LaunchMode.externalApplication);else await launchUrl(Uri.parse('https://wa.me/${phone218(customer.phone)}?text=${Uri.encodeComponent(msg)}'),mode:LaunchMode.externalApplication);}@override Widget build(BuildContext c){final items=store.transactions.where((t)=>t.customerId==customer.id).toList()..sort((a,b)=>b.date.compareTo(a.date));return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(customer.name)),body:ListView(padding:const EdgeInsets.all(12),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[const Text('الرصيد'),Text(money(store.balance(customer.id)),style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),Text('الدين ${money(store.debts(customer.id))} • المسدد ${money(store.paid(customer.id))}'),Wrap(spacing:8,children:[FilledButton.icon(onPressed:wa,icon:const Icon(Icons.chat),label:const Text('واتساب')),OutlinedButton.icon(onPressed:()=>launchUrl(Uri.parse('tel:${customer.phone}')),icon:const Icon(Icons.phone),label:const Text('اتصال'))])]))),...items.map((t)=>Card(child:ListTile(title:Text(t.type=='debt'?'دَين':'تسديد'),subtitle:Text('${dateText(t.date)}${t.note.isEmpty?'':' • ${t.note}'}'),leading:Icon(t.type=='debt'?Icons.arrow_downward:Icons.arrow_upward),trailing:Row(mainAxisSize:MainAxisSize.min,children:[if(t.receiptPath.isNotEmpty&&File(t.receiptPath).existsSync())IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ReceiptPage(path:t.receiptPath))),icon:const Icon(Icons.receipt_long_outlined)),Text(money(t.amount))]))))]),floatingActionButton:FloatingActionButton.extended(onPressed:store.locked?()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ActivationPage(store:store))):()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>AddTransactionPage(store:store,customer:customer))),icon:Icon(store.locked?Icons.lock_outline:Icons.add),label:Text(store.locked?'التفعيل':'عملية'))));}}

class AddTransactionPage extends StatefulWidget{const AddTransactionPage({super.key,required this.store,required this.customer});final Store store;final Customer customer;@override State<AddTransactionPage> createState()=>_AddTransactionPageState();}
class _AddTransactionPageState extends State<AddTransactionPage>{final amount=TextEditingController(),note=TextEditingController(),voiceText=TextEditingController();final picker=ImagePicker();final speech=stt.SpeechToText();String type='debt',receiptPath='',receiptUrl='';bool listening=false;
Future<void> voice()async{if(listening){await speech.stop();setState(()=>listening=false);return;}final ok=await speech.initialize(onStatus:(x){if(mounted)setState(()=>listening=x=='listening');},onError:(_){if(mounted)setState(()=>listening=false);});if(!ok){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تعذر تشغيل الميكروفون')));return;}setState(()=>listening=true);await speech.listen(localeId:'ar-LY',partialResults:true,onResult:(r){voiceText.text=r.recognizedWords;final m=RegExp(r'(\d+(?:[.,]\d+)?)').firstMatch(r.recognizedWords);if(m!=null)amount.text=m.group(1)!.replaceAll(',','.');if(r.finalResult&&mounted)setState(()=>listening=false);});}
Future<void> receipt()async{final src=await showModalBottomSheet<ImageSource>(context:context,builder:(c)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(leading:const Icon(Icons.camera_alt),title:const Text('تصوير الإيصال'),onTap:()=>Navigator.pop(c,ImageSource.camera)),ListTile(leading:const Icon(Icons.photo_library),title:const Text('اختيار من المعرض'),onTap:()=>Navigator.pop(c,ImageSource.gallery))])));if(src==null)return;final x=await picker.pickImage(source:src,imageQuality:85,maxWidth:1800,maxHeight:2400);if(x==null)return;final dir=await getApplicationDocumentsDirectory();final rd=Directory('${dir.path}/receipts');await rd.create(recursive:true);final f=await File(x.path).copy('${rd.path}/receipt_${DateTime.now().microsecondsSinceEpoch}.jpg');receiptPath=f.path;if(widget.store.firebaseReady){try{final r=FirebaseStorage.instance.ref('users/${widget.store.uid}/receipts/${f.uri.pathSegments.last}');await r.putFile(f);receiptUrl=await r.getDownloadURL();}catch(_){}}if(mounted)setState((){});}
Future<void> save()async{if(widget.store.locked){Navigator.pop(context);return;}final a=double.tryParse(amount.text.replaceAll(',','.'))??0;if(a<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('أدخل مبلغًا صحيحًا')));return;}if(type=='debt'&&widget.customer.limit>0){final b=widget.store.balance(widget.customer.id);if(b+a>widget.customer.limit){final avail=max(0.0,widget.customer.limit-b);await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('تجاوز السقف الائتماني'),content:Text('لا يمكن تسجيل الدين. السقف ${money(widget.customer.limit)} والمتاح ${money(avail)}.'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('حسنًا'))]));return;}}widget.store.transactions.add(Tx(id:makeId(),customerId:widget.customer.id,type:type,amount:a,date:DateTime.now(),note:note.text.trim(),receiptPath:receiptPath,receiptUrl:receiptUrl));await widget.store.save();if(mounted)Navigator.pop(context);}
@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(type=='debt'?'إضافة دَين':'تسجيل تسديد')),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(title:Text(widget.customer.name),subtitle:Text('الرصيد ${money(widget.store.balance(widget.customer.id))}'),trailing:widget.customer.limit>0?Text('السقف ${money(widget.customer.limit)}'):null)),const SizedBox(height:10),SegmentedButton<String>(segments:const[ButtonSegment(value:'debt',label:Text('دَين')),ButtonSegment(value:'payment',label:Text('تسديد'))],selected:{type},onSelectionChanged:(v)=>setState(()=>type=v.first)),TextField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'المبلغ بالدينار الليبي')),TextField(controller:note,decoration:const InputDecoration(labelText:'ملاحظات')),const SizedBox(height:8),OutlinedButton.icon(onPressed:voice,icon:Icon(listening?Icons.stop:Icons.mic),label:Text(listening?'إيقاف التسجيل':'تسجيل العملية بالصوت')),if(voiceText.text.isNotEmpty)TextField(controller:voiceText,readOnly:true,decoration:const InputDecoration(labelText:'النص المسموع')),const SizedBox(height:8),Card(child:ListTile(leading:const Icon(Icons.receipt_long),title:const Text('صورة الإيصال اختيارية'),subtitle:Text(receiptPath.isEmpty?'التقاط صورة من داخل التطبيق أو اختيارها':'تم إرفاق الإيصال'),trailing:IconButton(onPressed:receipt,icon:const Icon(Icons.add_a_photo)))),if(receiptPath.isNotEmpty)Padding(padding:const EdgeInsets.only(top:8),child:ClipRRect(borderRadius:BorderRadius.circular(12),child:Image.file(File(receiptPath),height:180,fit:BoxFit.contain))),const SizedBox(height:20),FilledButton(onPressed:save,child:const Text('حفظ العملية'))]));}
}

class SettingsPage extends StatefulWidget{const SettingsPage({super.key,required this.store});final Store store;@override State<SettingsPage> createState()=>_SettingsPageState();}
class _SettingsPageState extends State<SettingsPage>{late TextEditingController shop,msg;int taps=0;DateTime? last;@override void initState(){super.initState();shop=TextEditingController(text:widget.store.shop);msg=TextEditingController(text:widget.store.whatsappMessage);}void hidden(){final n=DateTime.now();if(last==null||n.difference(last!).inSeconds>2)taps=0;last=n;taps++;if(taps>=3){taps=0;showDialog(context:context,builder:(_)=>AdminGate(store:widget.store));}}Future<void>save()async{widget.store.shop=shop.text.trim().isEmpty?'DainPay — دَيْن':shop.text.trim();widget.store.whatsappMessage=msg.text.trim();await widget.store.save();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم الحفظ')));}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:GestureDetector(onTap:hidden,child:const Text('الإعدادات'))),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:shop,decoration:const InputDecoration(labelText:'اسم المحل / النشاط')),TextField(controller:msg,maxLines:4,decoration:const InputDecoration(labelText:'رسالة واتساب')),const SizedBox(height:12),Card(child:ListTile(title:const Text('المظهر'),subtitle:const Text('يتبع مظهر الجهاز تلقائيًا'),trailing:Icon(Icons.brightness_auto)),),Card(child:ListTile(title:const Text('رقم الجهاز'),subtitle:Text(widget.store.deviceId),trailing:IconButton(icon:const Icon(Icons.chat),onPressed:()=>launchUrl(Uri.parse('https://wa.me/218934951072?text=${Uri.encodeComponent('طلب تفعيل DainPay - رقم الجهاز: ${widget.store.deviceId}')}'),mode:LaunchMode.externalApplication)))),FilledButton(onPressed:save,child:const Text('حفظ الإعدادات')),const SizedBox(height:12),OutlinedButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ActivationPage(store:widget.store))),child:const Text('الاشتراك والتفعيل'))]));}}

class ActivationPage extends StatefulWidget{const ActivationPage({super.key,required this.store});final Store store;@override State<ActivationPage> createState()=>_ActivationPageState();}
class _ActivationPageState extends State<ActivationPage>{final code=TextEditingController();bool busy=false;Future<void>activate()async{setState(()=>busy=true);final ok=await widget.store.activate(code.text);setState(()=>busy=false);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ok?'تم التفعيل الدائم بنجاح':'الكود غير صحيح أو مستخدم أو غير مرتبط بهذا الجهاز')));if(ok&&mounted)Navigator.pop(context);}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('الاشتراك والتفعيل')),body:ListView(padding:const EdgeInsets.all(18),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.store.activated?'التطبيق مفعّل دائمًا':'الفترة التجريبية: ${widget.store.trialDaysLeft} أيام',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('الدفع نقدًا فقط. لا توجد بطاقات أو تحويلات.'),const SizedBox(height:8),Text('رقم الجهاز: ${widget.store.deviceId}')]))),const SizedBox(height:12),FilledButton.icon(onPressed:()=>launchUrl(Uri.parse('https://wa.me/218934951072?text=${Uri.encodeComponent('طلب تفعيل DainPay - رقم الجهاز: ${widget.store.deviceId}')}'),mode:LaunchMode.externalApplication),icon:const Icon(Icons.chat),label:const Text('طلب التفعيل عبر واتساب')),const SizedBox(height:18),TextField(controller:code,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'كود التفعيل')),const SizedBox(height:10),FilledButton(onPressed:busy?null:activate,child:Text(busy?'جارٍ التحقق...':'تفعيل دائم'))]));}

class AdminGate extends StatefulWidget{const AdminGate({super.key,required this.store});final Store store;@override State<AdminGate> createState()=>_AdminGateState();}
class _AdminGateState extends State<AdminGate>{final pin=TextEditingController();void enter(){if(pin.text=='116936'){Navigator.pop(context);Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminPage(store:widget.store)));}else{ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('رمز المالك غير صحيح')));}}@override Widget build(BuildContext c)=>AlertDialog(title:const Text('Adreemk'),content:TextField(controller:pin,obscureText:true,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'رمز المالك')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('إلغاء')),FilledButton(onPressed:enter,child:const Text('دخول'))]);}

class AdminPage extends StatefulWidget{const AdminPage({super.key,required this.store});final Store store;@override State<AdminPage> createState()=>_AdminPageState();}
class _AdminPageState extends State<AdminPage>{final d=TextEditingController();String generated='';Future<void>gen()async{final x=await widget.store.generateCode(d.text);setState(()=>generated=x??'تعذر التوليد');}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('Adreemk — إدارة التفعيل')),body:ListView(padding:const EdgeInsets.all(16),children:[const Text('توليد رمز دائم للعميل',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:10),TextField(controller:d,decoration:const InputDecoration(labelText:'رقم جهاز العميل')),const SizedBox(height:10),FilledButton.icon(onPressed:gen,icon:const Icon(Icons.key),label:const Text('توليد رمز')),if(generated.isNotEmpty)Card(child:ListTile(title:const Text('رمز التفعيل'),subtitle:Text(generated,style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold)),trailing:IconButton(onPressed:()=>launchUrl(Uri.parse('https://wa.me/${phone218('0934951072')}?text=${Uri.encodeComponent('رمز تفعيل DainPay: $generated')}'),mode:LaunchMode.externalApplication),icon:const Icon(Icons.send))))]));}

class ReceiptPage extends StatelessWidget{const ReceiptPage({super.key,required this.path});final String path;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الإيصال')),body:Center(child:InteractiveViewer(child:Image.file(File(path)))));}
