import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try { await Firebase.initializeApp(); } catch (_) {}
  final store = await Store.load();
  await store.firebaseConnect();
  runApp(DainPay(store));
}
String uid() => '${DateTime.now().microsecondsSinceEpoch}_${Random().nextInt(99999)}';
String money(double n) => '${n.toStringAsFixed(2)} د.ل';
String day(DateTime d) => '${d.day.toString().padLeft(2,'0')}/${d.month.toString().padLeft(2,'0')}/${d.year}';

class Customer {
  String id,name,phone; double limit;
  Customer(this.id,this.name,this.phone,[this.limit=0]);
  Map<String,dynamic> json()=>{'id':id,'name':name,'phone':phone,'limit':limit};
  factory Customer.from(Map<String,dynamic> j)=>Customer('${j['id']??''}','${j['name']??''}','${j['phone']??''}',(j['limit'] as num?)?.toDouble()??0);
}
class Tx {
  String id,customerId,type,note,receipt; double amount; DateTime date;
  Tx(this.id,this.customerId,this.type,this.amount,this.date,this.note,[this.receipt='']);
  Map<String,dynamic> json()=>{'id':id,'customerId':customerId,'type':type,'amount':amount,'date':date.toIso8601String(),'note':note,'receipt':receipt};
  factory Tx.from(Map<String,dynamic> j)=>Tx('${j['id']??''}','${j['customerId']??''}','${j['type']??'debt'}',(j['amount'] as num?)?.toDouble()??0,DateTime.tryParse('${j['date']}')??DateTime.now(),'${j['note']??''}','${j['receipt']??''}');
}
class Store extends ChangeNotifier {
  late SharedPreferences p; List<Customer> customers=[]; List<Tx> tx=[]; String shop='DainPay — دَيْن';
  String msg='السلام عليكم [الاسم]، تذكير لطيف بخصوص المتبقي عليكم قدره [المبلغ] د.ل.'; bool dark=false; String cloudUid=''; bool firebase=false, syncing=false;
  static Future<Store> load() async { final s=Store(); s.p=await SharedPreferences.getInstance(); s.shop=s.p.getString('shop')??s.shop; s.msg=s.p.getString('msg')??s.msg; s.dark=s.p.getBool('dark')??false;
    try{s.customers=(jsonDecode(s.p.getString('customers')??'[]') as List).map((e)=>Customer.from(Map<String,dynamic>.from(e))).toList();}catch(_){ }
    try{s.tx=(jsonDecode(s.p.getString('tx')??'[]') as List).map((e)=>Tx.from(Map<String,dynamic>.from(e))).toList();}catch(_){ } return s; }
  Future<void> firebaseConnect() async { try{ User? u=FirebaseAuth.instance.currentUser; u??=(await FirebaseAuth.instance.signInAnonymously()).user; if(u==null)return; cloudUid=u.uid; firebase=true; await pull(); }catch(_){firebase=false;} notifyListeners(); }
  CollectionReference<Map<String,dynamic>> get cr=>FirebaseFirestore.instance.collection('users').doc(cloudUid).collection('customers');
  CollectionReference<Map<String,dynamic>> get tr=>FirebaseFirestore.instance.collection('users').doc(cloudUid).collection('transactions');
  Future<void> pull() async { if(!firebase||cloudUid.isEmpty||syncing)return; syncing=true; try{ final a=await cr.get(), b=await tr.get(); for(final d in a.docs){final c=Customer.from(d.data()); final i=customers.indexWhere((x)=>x.id==c.id); if(i<0)customers.add(c);else customers[i]=c;} for(final d in b.docs){final x=d.data(); final raw=x['date']; final dt=raw is Timestamp?raw.toDate():DateTime.tryParse('$raw')??DateTime.now(); final t=Tx('${x['id']??d.id}','${x['customerId']??''}','${x['type']??'debt'}',(x['amount'] as num?)?.toDouble()??0,dt,'${x['note']??''}','${x['receipt']??''}'); final i=tx.indexWhere((z)=>z.id==t.id); if(i<0)tx.add(t);else tx[i]=t;} await local(); }catch(_){ } syncing=false; }
  Future<void> cloudSave() async { if(!firebase||cloudUid.isEmpty||syncing)return; syncing=true; try{final b=FirebaseFirestore.instance.batch(); for(final c in customers)b.set(cr.doc(c.id),c.json()); for(final t in tx)b.set(tr.doc(t.id),{...t.json(),'date':Timestamp.fromDate(t.date)}); await b.commit();}catch(_){ }syncing=false; }
  Future<void> local() async {await p.setString('customers',jsonEncode(customers.map((e)=>e.json()).toList()));await p.setString('tx',jsonEncode(tx.map((e)=>e.json()).toList()));await p.setString('shop',shop);await p.setString('msg',msg);await p.setBool('dark',dark);}
  Future<void> save() async {await local();notifyListeners();await cloudSave();}
  double balance(String id)=>tx.where((x)=>x.customerId==id).fold(0.0,(v,x)=>v+(x.type=='debt'?x.amount:-x.amount));
  double debts(String id)=>tx.where((x)=>x.customerId==id&&x.type=='debt').fold(0.0,(v,x)=>v+x.amount);
  double paid(String id)=>tx.where((x)=>x.customerId==id&&x.type=='payment').fold(0.0,(v,x)=>v+x.amount);
  String risk(String id){final b=balance(id);if(b<=0)return'مسدد';final a=tx.where((x)=>x.customerId==id&&x.type=='debt').toList()..sort((a,b)=>b.date.compareTo(a.date));if(a.isEmpty)return'حديث';final d=DateTime.now().difference(a.first.date).inDays;return d>90?'خطر':d>30?'متأخر':'حديث';}
}
class DainPay extends StatelessWidget {final Store s;const DainPay(this.s,{super.key}); ThemeData th(Brightness b)=>ThemeData(useMaterial3:true,brightness:b,colorSchemeSeed:const Color(0xFF0F5C6E),fontFamily:'Cairo'); @override Widget build(BuildContext c)=>AnimatedBuilder(animation:s,builder:(_,__)=>MaterialApp(debugShowCheckedModeBanner:false,theme:th(Brightness.light),darkTheme:th(Brightness.dark),themeMode:s.dark?ThemeMode.dark:ThemeMode.light,home:Home(s)));}
class Home extends StatefulWidget {final Store s;const Home(this.s,{super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{String q='',filter='all';@override Widget build(BuildContext c){final s=widget.s;final list=s.customers.where((x){final b=s.balance(x.id);return(q.isEmpty||x.name.contains(q)||x.phone.contains(q))&&(filter=='all'||filter=='debt'&&b>0||filter=='paid'&&b<=0);}).toList()..sort((a,b)=>s.balance(b.id).compareTo(s.balance(a.id)));final total=s.customers.fold<double>(0,(v,x)=>v+max(0,s.balance(x.id)));return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(s.shop,style:const TextStyle(fontWeight:FontWeight.bold)),actions:[IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Settings(s))),icon:const Icon(Icons.settings))]),body:ListView(padding:const EdgeInsets.all(12),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:Stat('المتبقي',money(total))),Expanded(child:Stat('العملاء','${s.customers.length}'))]))),TextField(decoration:const InputDecoration(hintText:'بحث بالاسم أو الهاتف',prefixIcon:Icon(Icons.search)),onChanged:(v)=>setState(()=>q=v)),const SizedBox(height:8),Wrap(spacing:8,children:[ChoiceChip(label:const Text('الكل'),selected:filter=='all',onSelected:(_)=>setState(()=>filter='all')),ChoiceChip(label:const Text('عليهم دين'),selected:filter=='debt',onSelected:(_)=>setState(()=>filter='debt')),ChoiceChip(label:const Text('مسدد'),selected:filter=='paid',onSelected:(_)=>setState(()=>filter='paid'))]),...list.map((x)=>Card(child:ListTile(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>CustomerPage(s,x))),leading:CircleAvatar(child:Text(x.name.isEmpty?'؟':x.name[0])),title:Text(x.name),subtitle:Text('${x.phone}\n${s.risk(x.id)} • دين ${money(s.debts(x.id))} • مسدد ${money(s.paid(x.id))}'),isThreeLine:true,trailing:Text(money(s.balance(x.id)),style:const TextStyle(fontWeight:FontWeight.bold)))))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>AddCustomer(s))),icon:const Icon(Icons.person_add),label:const Text('عميل'))));}}
class Stat extends StatelessWidget{final String a,b;const Stat(this.a,this.b,{super.key});@override Widget build(BuildContext c)=>Column(children:[Text(a),Text(b,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))]);}
class AddCustomer extends StatefulWidget{final Store s;const AddCustomer(this.s,{super.key});@override State<AddCustomer> createState()=>_AddCustomerState();}
class _AddCustomerState extends State<AddCustomer>{final n=TextEditingController(),p=TextEditingController(),l=TextEditingController();Future<void>save()async{if(n.text.trim().isEmpty)return;widget.s.customers.add(Customer(uid(),n.text.trim(),p.text.trim(),double.tryParse(l.text.replaceAll(',','.'))??0));await widget.s.save();if(mounted)Navigator.pop(context);} @override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('إضافة عميل')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:n,decoration:const InputDecoration(labelText:'اسم العميل')),TextField(controller:p,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'رقم الهاتف')),TextField(controller:l,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'السقف الائتماني اختياري')),const SizedBox(height:20),FilledButton(onPressed:save,child:const Text('حفظ'))]))));}
class CustomerPage extends StatelessWidget{final Store s;final Customer x;const CustomerPage(this.s,this.x,{super.key});Future<void>wa()async{final p=x.phone.replaceAll(RegExp(r'[^0-9]'),'');final m=s.msg.replaceAll('[الاسم]',x.name).replaceAll('[المبلغ]',money(s.balance(x.id)));final u=Uri.parse('https://wa.me/$p?text=${Uri.encodeComponent(m)}');if(await canLaunchUrl(u))await launchUrl(u,mode:LaunchMode.externalApplication);} @override Widget build(BuildContext c){final items=s.tx.where((t)=>t.customerId==x.id).toList()..sort((a,b)=>b.date.compareTo(a.date));return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(x.name)),body:ListView(padding:const EdgeInsets.all(12),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Text('الرصيد'),Text(money(s.balance(x.id)),style:const TextStyle(fontSize:30,fontWeight:FontWeight.bold)),Text('الدين ${money(s.debts(x.id))} • المسدد ${money(s.paid(x.id))}'),Wrap(children:[FilledButton.icon(onPressed:wa,icon:const Icon(Icons.chat),label:const Text('واتساب')),OutlinedButton.icon(onPressed:()=>launchUrl(Uri.parse('tel:${x.phone}')),icon:const Icon(Icons.phone),label:const Text('اتصال'))])]))),...items.map((t)=>Card(child:ListTile(title:Text(t.type=='debt'?'دَين':'تسديد'),subtitle:Text('${day(t.date)} ${t.note}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[if(t.receipt.isNotEmpty&&File(t.receipt).existsSync())IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Receipt(t.receipt))),icon:const Icon(Icons.receipt)),Text(money(t.amount))]))))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>AddTx(s,x))),icon:const Icon(Icons.add),label:const Text('عملية'))));}}
class AddTx extends StatefulWidget{final Store s;final Customer x;const AddTx(this.s,this.x,{super.key});@override State<AddTx> createState()=>_AddTxState();}
class _AddTxState extends State<AddTx>{final amount=TextEditingController(),note=TextEditingController();final picker=ImagePicker();String type='debt',receipt='';Future<void>pick()async{final src=await showModalBottomSheet<ImageSource>(context:context,builder:(_)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(title:const Text('الكاميرا'),leading:const Icon(Icons.camera_alt),onTap:()=>Navigator.pop(context,ImageSource.camera)),ListTile(title:const Text('المعرض'),leading:const Icon(Icons.photo),onTap:()=>Navigator.pop(context,ImageSource.gallery))])));if(src==null)return;final image=await picker.pickImage(source:src,imageQuality:75,maxWidth:1600,maxHeight:2200);if(image==null)return;final d=await getApplicationDocumentsDirectory();final dir=Directory('${d.path}/receipts');await dir.create(recursive:true);final f=await File(image.path).copy('${dir.path}/${uid()}.jpg');if(mounted)setState(()=>receipt=f.path);}Future<void>save()async{final v=double.tryParse(amount.text.replaceAll(',','.'));if(v==null||v<=0)return;widget.s.tx.add(Tx(uid(),widget.x.id,type,v,DateTime.now(),note.text.trim(),receipt));await widget.s.save();if(mounted)Navigator.pop(context);}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text('عملية — ${widget.x.name}')),body:ListView(padding:const EdgeInsets.all(16),children:[SegmentedButton<String>(segments:const[ButtonSegment(value:'debt',label:Text('دَين')),ButtonSegment(value:'payment',label:Text('تسديد'))],selected:{type},onSelectionChanged:(v)=>setState(()=>type=v.first)),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'المبلغ بالدينار الليبي')),TextField(controller:note,maxLines:3,decoration:const InputDecoration(labelText:'ملاحظات')),Card(child:ListTile(title:const Text('صورة الإيصال'),subtitle:Text(receipt.isEmpty?'اختيارية':'تم الإرفاق'),trailing:IconButton(onPressed:pick,icon:const Icon(Icons.add_a_photo)))),if(receipt.isNotEmpty)Image.file(File(receipt),height:180,fit:BoxFit.cover),const SizedBox(height:16),FilledButton(onPressed:save,child:const Text('حفظ العملية'))]))));}
class Receipt extends StatelessWidget{final String path;const Receipt(this.path,{super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الإيصال')),body:Center(child:InteractiveViewer(child:Image.file(File(path)))));}
class Settings extends StatefulWidget{final Store s;const Settings(this.s,{super.key});@override State<Settings> createState()=>_SettingsState();}
class _SettingsState extends State<Settings>{late TextEditingController shop,msg;@override void initState(){super.initState();shop=TextEditingController(text:widget.s.shop);msg=TextEditingController(text:widget.s.msg);}Future<void>save()async{widget.s.shop=shop.text.trim().isEmpty?'DainPay — دَيْن':shop.text.trim();widget.s.msg=msg.text.trim();await widget.s.save();if(mounted)Navigator.pop(context);}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('الإعدادات')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:shop,decoration:const InputDecoration(labelText:'اسم المحل / النشاط')),SwitchListTile(title:const Text('المظهر الداكن'),value:widget.s.dark,onChanged:(v)async{widget.s.dark=v;await widget.s.save();setState((){});}),TextField(controller:msg,maxLines:4,decoration:const InputDecoration(labelText:'رسالة واتساب')),const SizedBox(height:20),FilledButton(onPressed:save,child:const Text('حفظ'))]))));}
