from pathlib import Path
import re
p=Path('lib/main.dart'); s=p.read_text()
def repl(a,b,body):
 global s
 pattern=rf'class {re.escape(a)}.*?(?=class {re.escape(b)})' if b else rf'class {re.escape(a)}.*$'
 s,n=re.subn(pattern,body+'\n',s,count=1,flags=re.S)
 if n!=1: raise SystemExit('replace failed: '+a)
repl('_HomePageState','AddCustomerPage',r'''class _HomePageState extends State<HomePage> {
 String query=''; String filter='all'; int taps=0; DateTime? lastTap;
 void hidden(){final n=DateTime.now();if(lastTap==null||n.difference(lastTap!).inSeconds>2)taps=0;lastTap=n;taps++;if(taps==3){taps=0;showDialog(context:context,builder:(_)=>AdminGate(store:widget.store));}}
 @override Widget build(BuildContext context){final s=widget.store;final list=s.customers.where((x){final b=s.balance(x.id);return(query.isEmpty||x.name.contains(query)||x.phone.contains(query))&&(filter=='all'||(filter=='debt'&&b>0)||(filter=='paid'&&b<=0));}).toList()..sort((a,b)=>s.balance(b.id).compareTo(s.balance(a.id)));return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:GestureDetector(onTap:hidden,child:Text(s.shop)),actions:[IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>SettingsPage(store:s))),icon:const Icon(Icons.settings_outlined))]),body:ListView(padding:const EdgeInsets.all(12),children:[if(!s.activated)Card(child:ListTile(title:Text(s.locked?'انتهت الفترة التجريبية':'التجربة المجانية 10 أيام'),subtitle:Text(s.locked?'يلزم التفعيل':'متبقٍ ${s.trialDaysLeft} أيام'),trailing:FilledButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ActivationPage(store:s))),child:const Text('تفعيل')))),TextField(decoration:const InputDecoration(hintText:'بحث بالاسم أو الهاتف',prefixIcon:Icon(Icons.search)),onChanged:(v)=>setState(()=>query=v)),Wrap(spacing:8,children:[ChoiceChip(label:const Text('الكل'),selected:filter=='all',onSelected:(_)=>setState(()=>filter='all')),ChoiceChip(label:const Text('عليهم دين'),selected:filter=='debt',onSelected:(_)=>setState(()=>filter='debt')),ChoiceChip(label:const Text('مسدد'),selected:filter=='paid',onSelected:(_)=>setState(()=>filter='paid'))]),...list.map((x)=>Card(child:ListTile(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>CustomerPage(store:s,customer:x))),title:Text(x.name),subtitle:Text('${x.phone}\n${s.risk(x.id)} • دين ${money(s.debts(x.id))} • مسدد ${money(s.paid(x.id))}'),isThreeLine:true,trailing:Text(money(s.balance(x.id))))))]),floatingActionButton:FloatingActionButton.extended(onPressed:s.locked?()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ActivationPage(store:s))):()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AddCustomerPage(store:s))),icon:Icon(s.locked?Icons.lock:Icons.person_add),label:Text(s.locked?'التفعيل':'عميل'))));}
}''')
repl('_AddCustomerPageState','CustomerPage',r'''class _AddCustomerPageState extends State<AddCustomerPage>{final name=TextEditingController(),phone=TextEditingController(),limit=TextEditingController();@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('إضافة عميل')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:name,decoration:const InputDecoration(labelText:'اسم العميل')),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'رقم الهاتف')),TextField(controller:limit,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'السقف الائتماني اختياري')),FilledButton(onPressed:()async{if(name.text.trim().isEmpty)return;widget.store.customers.add(Customer(id:makeId(),name:name.text.trim(),phone:phone.text.trim(),limit:double.tryParse(limit.text.replaceAll(',','.'))??0));await widget.store.save();if(context.mounted)Navigator.pop(context);},child:const Text('حفظ'))])));}}''')
repl('_SettingsPageState','ActivationPage',r'''class _SettingsPageState extends State<SettingsPage>{late TextEditingController shop,msg;int taps=0;DateTime? last;@override void initState(){super.initState();shop=TextEditingController(text:widget.store.shop);msg=TextEditingController(text:widget.store.whatsappMessage);}void hidden(){final n=DateTime.now();if(last==null||n.difference(last!).inSeconds>2)taps=0;last=n;taps++;if(taps==3)showDialog(context:context,builder:(_)=>AdminGate(store:widget.store));}Future<void>save()async{widget.store.shop=shop.text.trim();widget.store.whatsappMessage=msg.text.trim();await widget.store.save();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم الحفظ')));}@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:GestureDetector(onTap:hidden,child:const Text('الإعدادات'))),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:shop,decoration:const InputDecoration(labelText:'اسم المحل / النشاط')),const ListTile(title:Text('المظهر'),subtitle:Text('تلقائي حسب مظهر الجهاز'),trailing:Icon(Icons.brightness_auto)),TextField(controller:msg,maxLines:4,decoration:const InputDecoration(labelText:'رسالة واتساب')),Text('رقم الجهاز: ${widget.store.deviceId}'),FilledButton(onPressed:save,child:const Text('حفظ')),OutlinedButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ActivationPage(store:widget.store))),child:const Text('الاشتراك والتفعيل'))])));}}''')
repl('_ActivationPageState','AdminGate',r'''class _ActivationPageState extends State<ActivationPage>{final code=TextEditingController();bool busy=false;Future<void>go()async{setState(()=>busy=true);final ok=await widget.store.activateCode(code.text);if(mounted)setState(()=>busy=false);if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ok?'تم التفعيل الدائم':'الكود غير صحيح أو مستخدم أو مخصص لجهاز آخر')));if(ok)Navigator.pop(context);}@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('الاشتراك والتفعيل')),body:ListView(padding:const EdgeInsets.all(16),children:[Text(widget.store.activated?'مفعّل دائمًا':'التجربة المجانية: ${widget.store.trialDaysLeft} أيام',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Text('رقم الجهاز: ${widget.store.deviceId}'),const Text('الدفع نقدًا فقط'),FilledButton.icon(onPressed:()=>launchUrl(Uri.https('wa.me','/218934951072',{'text':'طلب تفعيل DainPay - رقم الجهاز: ${widget.store.deviceId}'}),mode:LaunchMode.externalApplication),icon:const Icon(Icons.chat),label:const Text('طلب التفعيل عبر واتساب')),TextField(controller:code,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'كود التفعيل')),FilledButton(onPressed:busy?null:go,child:Text(busy?'جارٍ التحقق':'تفعيل دائم'))])));}}''')
repl('_AdminGateState','AdminPage',r'''class _AdminGateState extends State<AdminGate>{final pin=TextEditingController();void enter(){if(pin.text=='116936'){Navigator.pop(context);Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminPage(store:widget.store)));}else{ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('رمز المالك غير صحيح')));}}@override Widget build(BuildContext context)=>AlertDialog(title:const Text('Adreemk'),content:TextField(controller:pin,obscureText:true,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'رمز المالك')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('إلغاء')),FilledButton(onPressed:enter,child:const Text('دخول'))]);}}''')
repl('_AdminPageState','__END__',r'''class _AdminPageState extends State<AdminPage>{final device=TextEditingController();String result='';Future<void>generate()async{final x=await widget.store.generateCode(device.text);if(mounted)setState(()=>result=x??'تعذر التوليد — تحقق من Firebase');}@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('Adreemk — المالك')),body:ListView(padding:const EdgeInsets.all(16),children:[const Text('توليد رمز دائم خاص بعميل واحد'),TextField(controller:device,decoration:const InputDecoration(labelText:'رقم جهاز العميل')),FilledButton(onPressed:generate,child:const Text('توليد الرمز')),if(result.isNotEmpty)Card(child:ListTile(title:const Text('رمز التفعيل'),subtitle:Text(result,style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold))))])));}}''')
p.write_text(s);print('PARSE_STEP1_SOURCE_REPAIRED')