from pathlib import Path
src = Path('tool/rewrite_main_v4.py').read_text()
start = src.index("ui=r'''") + len("ui=r'''")
end = src.index("'''\nprefix=", start)
t = src[start:end]
t = t.replace('AppStore', 'Store').replace('TransactionItem', 'Tx').replace('cleanPhone', 'phone218').replace('id()', 'makeId()')

def replace_block(text, begin, finish, replacement):
    a=text.index(begin); b=text.index(finish,a); return text[:a]+replacement+text[b:]

customer = '''class CustomerPage extends StatelessWidget {\n  const CustomerPage({super.key, required this.store, required this.customer});\n  final Store store; final Customer customer;\n  Future<void> sendWhatsApp() async {\n    final text=store.whatsappText.replaceAll('[الاسم]',customer.name).replaceAll('[المبلغ]',money(store.balance(customer.id)));\n    await launchUrl(Uri.https('wa.me','/${phone218(customer.phone)}',{'text':text}),mode:LaunchMode.externalApplication);\n  }\n  @override Widget build(BuildContext context){\n    final items=store.transactions.where((x)=>x.customerId==customer.id).toList();\n    items.sort((a,b)=>b.date.compareTo(a.date));\n    return Directionality(textDirection:TextDirection.rtl,child:Scaffold(\n      appBar:AppBar(title:Text(customer.name)),\n      body:ListView(padding:const EdgeInsets.all(12),children:[\n        Card(child:ListTile(title:Text(money(store.balance(customer.id)),style:const TextStyle(fontSize:26,fontWeight:FontWeight.bold)),subtitle:Text('دين ${money(store.debt(customer.id))} • مسدد ${money(store.paid(customer.id))}'),trailing:Wrap(children:[IconButton(onPressed:sendWhatsApp,icon:const Icon(Icons.chat)),IconButton(onPressed:(){launchUrl(Uri.parse('tel:${customer.phone}'));},icon:const Icon(Icons.phone))]))),\n        for(final item in items) ListTile(title:Text(item.type=='debt'?'دَين':'تسديد'),subtitle:Text('${dateText(item.date)} ${item.note}'),trailing:Text(money(item.amount))),\n      ]),\n      floatingActionButton:FloatingActionButton.extended(onPressed:store.locked?(){Navigator.push(context,MaterialPageRoute(builder:(context)=>ActivationPage(store:store)));}:(){Navigator.push(context,MaterialPageRoute(builder:(context)=>TransactionPage(store:store,customer:customer)));},icon:Icon(store.locked?Icons.lock:Icons.add),label:Text(store.locked?'التفعيل':'عملية')),\n    ));\n  }\n}\n'''
t=replace_block(t,'class CustomerPage extends StatelessWidget','class TransactionPage extends StatefulWidget',customer)

activation='''class ActivationPage extends StatefulWidget {\n  const ActivationPage({super.key,required this.store});\n  final Store store;\n  @override State<ActivationPage> createState()=>_ActivationPageState();\n}\nclass _ActivationPageState extends State<ActivationPage>{\n  final code=TextEditingController(); bool busy=false;\n  Future<void> activate() async {\n    setState((){busy=true;});\n    final ok=await widget.store.activateCode(code.text);\n    if(mounted)setState((){busy=false;});\n    if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ok?'تم التفعيل الدائم':'الكود غير صحيح أو مستخدم')));\n    if(ok&&mounted)Navigator.pop(context);\n  }\n  @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('الاشتراك والتفعيل')),body:ListView(padding:const EdgeInsets.all(16),children:[\n    Text(widget.store.activated?'مفعّل دائمًا':'التجربة المجانية: ${widget.store.trialDaysLeft} أيام',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),\n    Text('رقم الجهاز: ${widget.store.deviceId}'),\n    const Text('الدفع نقدًا فقط'),\n    FilledButton.icon(onPressed:(){launchUrl(Uri.parse('https://wa.me/218934951072?text=${Uri.encodeComponent('طلب تفعيل DainPay - رقم الجهاز: ${widget.store.deviceId}')}'),mode:LaunchMode.externalApplication);},icon:const Icon(Icons.chat),label:const Text('طلب التفعيل عبر واتساب')),\n    TextField(controller:code,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'كود التفعيل')),\n    FilledButton(onPressed:busy?null:activate,child:Text(busy?'جارٍ التحقق':'تفعيل دائم')),\n  ])));\n}\n'''
t=replace_block(t,'class ActivationPage extends StatefulWidget','class OwnerGate extends StatefulWidget',activation)

prefix=src[:src.index('class DainPayApp')]
prefix=prefix.replace("if(ts!=null) trialStart=DateTime.tryParse(ts); else {trialStart=DateTime.now();await s.prefs.setString('trial_start',trialStart!.toIso8601String());}","if(ts!=null){s.trialStart=DateTime.tryParse(ts);}else{s.trialStart=DateTime.now();await s.prefs.setString('trial_start',s.trialStart.toIso8601String());}")
Path('lib/main.dart').write_text(prefix+t)
